// export const InterestsData = [
//   {
//     label: 'Music',
//     sub: ['Concerts', 'Festivals', 'Live Music', 'Karaoke ', 'Afrobeats', 'Hip hop', 'R&B'],
//     id: 1,
//   },
//   {
//     label: 'Comedy',
//     sub: ['Comedy'],
//     id: 2,
//   },
//   {
//     label: 'Movies',
//     sub: ['American Films', 'Nigerian Films'],
//     id: 3,
//   },
//   {
//     label: 'Games',
//     sub: ['Board Games', 'Video Games', 'Arcade Games', 'Team Games'],
//     id: 4,
//   },
//   {
//     label: 'Nightlife',
//     sub: ['Clubs', 'Lounges', 'Bars', 'Rooftop', 'Outdoor'],
//     id: 5,
//   },
//   {
//     label: 'Parties',
//     sub: ['Block Parties', 'Day Parties', 'Beach Parties', 'Launch Parties'],
//     id: 6,
//   },
//   {
//     label: 'Art',
//     sub: ['Art Exhibitions', 'Galleries', 'Paintings', 'Photography', 'Writing', 'Poetry'],
//     id: 7,
//   },
//   {
//     label: 'Food & Drinks',
//     sub: [
//       'Fine Dining',
//       'Casual Dining',
//       'Contemporary Casual Dining',
//       'Family Style',
//       'Fast Casual',
//       'Fast Food',
//       'Cafe',
//       'Coffee House',
//       'Pub',
//       'Bistro',
//       'Buffet',
//       'Food Trucks',
//       'Rooftop',
//       'Waterside',
//       'Nigerian Food',
//       'Ghanaian Food',
//       'Greek Food',
//       'Ethiopian Food',
//       'Caribbean Food',
//       'Japanese Food',
//       'Chinese Food',
//       'American Food',
//       'Soul Food',
//       'French Food',
//       'Lebanese Food',
//       'Mediterranean Food',
//       'Spanish Food',
//       'Indian Food',
//       'Mexican Food',
//       'Thai Food',
//       'Italian Food',
//       'Street Food',
//       'Fusion Cuisine',
//       'Desserts',
//       'Food festivals',
//     ],
//     id: 8,
//   },
//   {
//     label: 'Fitness',
//     sub: [
//       'Bodybuilding',
//       'Running',
//       'Dancing',
//       'Cycling',
//       'Boxing',
//       'Kickboxing',
//       'Hiking',
//       'Swimming',
//       'Yoga',
//       'Pilates',
//       'Roller skating',
//     ],
//     id: 9,
//   },
//   {
//     label: 'Sports',
//     sub: [
//       'American football',
//       'Flag football',
//       'Baseball',
//       'Basketball',
//       'Volleyball',
//       'Cricket',
//       'Football(Soccer)',
//       'Field hockey',
//       'Golfing',
//       'Rowling',
//       'Rugby',
//       'Surfing',
//       'Tennis',
//       'Wrestling',
//       'Bowling',
//       'Gymnastics',
//     ],
//     id: 10,
//   },
//   {
//     label: 'Adventure',
//     sub: [
//       'Fishing',
//       'Horseback Riding',
//       'Paintball',
//       'Kayaking',
//       'Jet Skiing',
//       'Four Wheeling',
//       'Sailing',
//       'Parasailing',
//       'Snorkeling',
//       'Scuba Diving',
//       'Go Karting',
//       'Skydiving',
//       'Safaris',
//       'Wildlife',
//       'Nature',
//     ],
//     id: 11,
//   },
//   {
//     label: 'Travel',
//     sub: ['Travel'],
//     id: 12,
//   },
//   {
//     label: 'Fashion',
//     sub: ['Fashion Shows', 'Popup Shops', 'Shopping', 'Markets', 'Fashion Classes'],
//     id: 13,
//   },
//   {
//     label: 'Beauty',
//     sub: ['Hair', 'Makeup', 'Nails', 'Skincare'],
//     id: 14,
//   },
//   {
//     label: 'Wellness',
//     sub: ['Spas', 'Retreats', 'Massages', 'Specialty Treatments'],
//     id: 15,
//   },
//   {
//     label: 'Culture',
//     sub: ['Native festivals', 'Native traditions', 'Language', 'Historic attractions', 'Local tours'],
//     id: 16,
//   },
//   {
//     label: 'Community',
//     sub: ['Volunteering', 'Activism', 'Environment'],
//     id: 17,
//   },
//   {
//     label: 'Business',
//     sub: ['Conferences', 'Seminars', 'Workshops', 'Trade Shows', 'Networking', 'Business Events'],
//     id: 18,
//   },
// ];
export const InterestsData = [
  {
    label: 'Sports & Fitness',
    id: 1,
  },
  {
    label: 'Recreational/Art',
    id: 2,
  },
  {
    label: 'Entertainment/Social',
    id: 3,
  },
  {
    label: 'Educational',
    id: 4,
  },
  {
    label: 'Community',
    id: 5,
  },
  {
    label: 'Food/Drink',
    id: 6,
  },
  {
    label: 'Restaurants',
    id: 7,
  },
  {
    label: 'Activities/Events',
    id: 8,
  },
];
